name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nada818/testrepo:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: nada818
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image to Docker Hub
      run: docker push nada818/environnement:$(date +%s)
